[package]
name = "caustic"
description = "Placeholder"
license = "MIT"
version = "0.0.1"
authors = ["Agro Rachmatullah <agro1986@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
